"""
FastAPI service layer.

Every mutating/data-facing endpoint requires the X-API-Key header and
is rate-limited. Run with:
    uvicorn app.main:app --reload
Docs at /docs (auto-generated by FastAPI/Swagger).
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager

import numpy as np
from fastapi import Depends, FastAPI, HTTPException
from pydantic import BaseModel, Field

from app.drift_monitor import DriftMonitor
from app.feedback_loop import record_outcome, retraining_readiness
from app.orchestrator import process_dispute
from app.scorer import evaluate, load_dataset
from app.security import rate_limit, require_api_key

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("verigate")

# --- Model + drift monitor loaded once at startup, not per-request ---
_state: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    report, scorer = evaluate()
    rows, X, y, amounts = load_dataset()
    probs = scorer.model.predict_proba(X)[:, 1]
    baseline_mean, baseline_std = float(np.mean(probs)), float(np.std(probs))

    _state["scorer"] = scorer
    _state["eval_report"] = report
    _state["drift_monitor"] = DriftMonitor(baseline_mean=baseline_mean, baseline_std=baseline_std)
    logger.info("Model loaded. Eval report: %s", report)

    yield  # app runs here

    _state.clear()  # cleanup on shutdown


app = FastAPI(
    title="verigate-cb",
    description="Chargeback evidence responder with an anti-hallucination verifier gate.",
    version="1.0.0",
    lifespan=lifespan,
)


class EvidenceIn(BaseModel):
    delivery_confirmation: bool = False
    signature_matches_cardholder: bool = False
    ip_matches_billing_country: bool = False
    prior_clean_order_count: int = Field(default=0, ge=0, le=1000)
    support_chat_exists: bool = False
    refund_already_issued: bool = False
    device_fingerprint_reused: bool = False


class DisputeIn(BaseModel):
    dispute_id: str = Field(..., min_length=1, max_length=64)
    reason_code: str = Field(..., min_length=1, max_length=64)
    amount_inr: int = Field(..., gt=0, le=10_000_000)  # sanity bound, not a real payments limit
    evidence: EvidenceIn


class FeedbackIn(BaseModel):
    dispute_id: str = Field(..., min_length=1, max_length=64)
    actual_outcome: str = Field(..., pattern="^(won|lost)$")
    reviewer_note: str = Field(default="", max_length=1000)


@app.get("/health")
def health():
    """Unauthenticated — for load balancer / uptime checks only."""
    return {"status": "ok"}


@app.post("/disputes/process", dependencies=[Depends(require_api_key), Depends(rate_limit)])
def process(dispute: DisputeIn):
    if "scorer" not in _state:
        raise HTTPException(status_code=503, detail="Model not loaded yet.")

    record = process_dispute(
        dispute.model_dump(),
        _state["scorer"],
        _state["drift_monitor"],
    )
    return record


@app.get("/model/eval-report", dependencies=[Depends(require_api_key)])
def eval_report():
    return _state.get("eval_report", {})


@app.post("/feedback", dependencies=[Depends(require_api_key), Depends(rate_limit)])
def submit_feedback(feedback: FeedbackIn):
    record = record_outcome(feedback.dispute_id, feedback.actual_outcome, feedback.reviewer_note)
    return record


@app.get("/feedback/retraining-readiness", dependencies=[Depends(require_api_key)])
def retraining_status():
    return retraining_readiness()
