import { DisputeRecord } from "@/types/dispute";

export const mockDisputes: DisputeRecord[] = [
  {
    timestamp: 1788441890.929,
    dispute_id: "CB-2201",
    reason_code: "product_not_received",
    amount_inr: 15000,
    winnability_probability: 0.925,
    threshold_applied: 0.8,
    explanation: [
      { factor: "Signature matches cardholder", contribution: 2.074, direction: "supports winning" },
      { factor: "Delivery confirmation on file", contribution: 1.883, direction: "supports winning" },
      { factor: "IP matches billing country", contribution: 0.573, direction: "supports winning" },
      { factor: "Prior clean order history", contribution: 0.27, direction: "supports winning" },
      { factor: "Support chat log exists", contribution: 0.02, direction: "supports winning" },
    ],
    integrity_consistent: true,
    integrity_flags: [],
    cited_claims: ["DELIVERY_CONFIRMED", "SIGNATURE_MATCH", "IP_MATCH", "REPEAT_CUSTOMER", "NO_PRIOR_REFUND"],
    verifier_approved: true,
    verifier_reason: "All cited claims backed by evidence.",
    drift_detected: false,
    decision: "AUTO_SUBMIT",
    letter:
      "We respectfully submit the following evidence in response to this dispute:\n- Delivery confirmation is on file for this order.\n- The delivery signature matches the cardholder's name on file.\n- The originating IP address for this order matches the billing country.\n- The cardholder has 5 prior clean orders with no disputes.\n- No refund has been issued for this transaction.",
    evidence: {
      delivery_confirmation: true,
      signature_matches_cardholder: true,
      ip_matches_billing_country: true,
      prior_clean_order_count: 5,
      support_chat_exists: true,
      refund_already_issued: false,
      device_fingerprint_reused: false,
    },
  },
  {
    timestamp: 1788441780.1,
    dispute_id: "CB-2198",
    reason_code: "product_unacceptable",
    amount_inr: 42500,
    winnability_probability: 0.74,
    threshold_applied: 0.83,
    explanation: [
      { factor: "Delivery confirmation on file", contribution: 1.883, direction: "supports winning" },
      { factor: "Signature matches cardholder", contribution: 2.074, direction: "supports winning" },
      { factor: "Device fingerprint reused", contribution: -1.1, direction: "hurts winning" },
    ],
    integrity_consistent: true,
    integrity_flags: [],
    cited_claims: ["DELIVERY_CONFIRMED", "SIGNATURE_MATCH"],
    verifier_approved: false,
    verifier_reason:
      "Draft cites ['SIGNATURE_MATCH'] which the retrieved evidence does not support.",
    drift_detected: false,
    decision: "ESCALATE_VERIFICATION_FAILED",
    letter:
      "We respectfully submit the following evidence in response to this dispute:\n- Delivery confirmation is on file for this order.\n- The delivery signature matches the cardholder's name on file.",
    evidence: {
      delivery_confirmation: true,
      signature_matches_cardholder: false,
      ip_matches_billing_country: true,
      prior_clean_order_count: 1,
      support_chat_exists: false,
      refund_already_issued: false,
      device_fingerprint_reused: true,
    },
  },
  {
    timestamp: 1788441600.4,
    dispute_id: "CB-2190",
    reason_code: "fraud",
    amount_inr: 3200,
    winnability_probability: 0.31,
    threshold_applied: 0.75,
    explanation: [
      { factor: "Delivery confirmation on file", contribution: -1.0, direction: "hurts winning" },
      { factor: "IP matches billing country", contribution: -0.6, direction: "hurts winning" },
    ],
    integrity_consistent: true,
    integrity_flags: [],
    cited_claims: [],
    verifier_approved: true,
    verifier_reason: "All cited claims backed by evidence.",
    drift_detected: false,
    decision: "ESCALATE_LOW_CONFIDENCE",
    letter: "Insufficient evidence to contest this dispute. Recommend accepting the chargeback.",
    evidence: {
      delivery_confirmation: false,
      signature_matches_cardholder: false,
      ip_matches_billing_country: false,
      prior_clean_order_count: 0,
      support_chat_exists: false,
      refund_already_issued: false,
      device_fingerprint_reused: false,
    },
  },
  {
    timestamp: 1788441500.2,
    dispute_id: "CB-2184",
    reason_code: "duplicate_charge",
    amount_inr: 899,
    winnability_probability: 0.68,
    threshold_applied: 0.75,
    explanation: [
      { factor: "Signature matches cardholder", contribution: 2.074, direction: "supports winning" },
    ],
    integrity_consistent: false,
    integrity_flags: ["signature_match_without_delivery_confirmation"],
    cited_claims: ["SIGNATURE_MATCH"],
    verifier_approved: false,
    verifier_reason: "Draft cites ['SIGNATURE_MATCH'] which the retrieved evidence does not support.",
    drift_detected: false,
    decision: "ESCALATE_INTEGRITY_FAILED",
    letter: "We respectfully submit the following evidence in response to this dispute:\n- The delivery signature matches the cardholder's name on file.",
    evidence: {
      delivery_confirmation: false,
      signature_matches_cardholder: true,
      ip_matches_billing_country: true,
      prior_clean_order_count: 2,
      support_chat_exists: false,
      refund_already_issued: false,
      device_fingerprint_reused: false,
    },
  },
];

export const mockEvalReport = {
  precision: 0.934,
  recall: 0.866,
  f1: 0.899,
  test_set_size: 150,
  false_positive_cost_inr: 2500,
  revenue_recovered_inr: 1446410,
  revenue_recoverable_inr: 1663215,
  recovery_rate: 0.87,
};
